# Generated by Django 4.2.7 on 2023-11-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_user_managers_user_groups_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Unclassified', 'Unclassified'), ('Scientific', 'Scientific'), ('Novel', 'Novel')], default='Unclassified', max_length=12),
        ),
    ]
