# Generated by Django 4.2.7 on 2023-11-14 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='File')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_covers', to='books.book')),
            ],
        ),
    ]
